/* Generated By:JavaCC: Do not edit this line. CCALParserVisitor.java Version 5.0 */
public interface CCALParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Program node, Object data);
  public Object visit(DeclList node, Object data);
  public Object visit(VarDecl node, Object data);
  public Object visit(ConstDecl node, Object data);
  public Object visit(FunctionList node, Object data);
  public Object visit(Function node, Object data);
  public Object visit(Return node, Object data);
  public Object visit(Type node, Object data);
  public Object visit(ParamList node, Object data);
  public Object visit(NempParamList node, Object data);
  public Object visit(Main node, Object data);
  public Object visit(StatementBlock node, Object data);
  public Object visit(Assignment node, Object data);
  public Object visit(FuncCall node, Object data);
  public Object visit(Statement node, Object data);
  public Object visit(Skip node, Object data);
  public Object visit(BoolOp node, Object data);
  public Object visit(NegateIdent node, Object data);
  public Object visit(Boolean node, Object data);
  public Object visit(ArithOp node, Object data);
  public Object visit(CompOp node, Object data);
  public Object visit(ArgList node, Object data);
  public Object visit(LIdent node, Object data);
  public Object visit(RIdent node, Object data);
  public Object visit(Ident node, Object data);
  public Object visit(Number node, Object data);
  public Object visit(OpenBlock node, Object data);
  public Object visit(CloseBlock node, Object data);
}
/* JavaCC - OriginalChecksum=f3b790018f7fa5b1a6d14865fbc0510e (do not edit this line) */
