/* Generated By:JavaCC: Do not edit this line. CCALParserTreeConstants.java Version 5.0 */
public interface CCALParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLLIST = 1;
  public int JJTVOID = 2;
  public int JJTVARDECL = 3;
  public int JJTCONSTDECL = 4;
  public int JJTFUNCTIONLIST = 5;
  public int JJTFUNCTION = 6;
  public int JJTRETURN = 7;
  public int JJTTYPE = 8;
  public int JJTPARAMLIST = 9;
  public int JJTNEMPPARAMLIST = 10;
  public int JJTMAIN = 11;
  public int JJTSTATEMENTBLOCK = 12;
  public int JJTASSIGNMENT = 13;
  public int JJTFUNCCALL = 14;
  public int JJTSTATEMENT = 15;
  public int JJTSKIP = 16;
  public int JJTBOOLOP = 17;
  public int JJTNEGATEIDENT = 18;
  public int JJTBOOLEAN = 19;
  public int JJTARITHOP = 20;
  public int JJTCOMPOP = 21;
  public int JJTARGLIST = 22;
  public int JJTLIDENT = 23;
  public int JJTRIDENT = 24;
  public int JJTIDENT = 25;
  public int JJTNUMBER = 26;
  public int JJTOPENBLOCK = 27;
  public int JJTCLOSEBLOCK = 28;


  public String[] jjtNodeName = {
    "Program",
    "DeclList",
    "void",
    "VarDecl",
    "ConstDecl",
    "FunctionList",
    "Function",
    "Return",
    "Type",
    "ParamList",
    "NempParamList",
    "Main",
    "StatementBlock",
    "Assignment",
    "FuncCall",
    "Statement",
    "Skip",
    "BoolOp",
    "NegateIdent",
    "Boolean",
    "ArithOp",
    "CompOp",
    "ArgList",
    "LIdent",
    "RIdent",
    "Ident",
    "Number",
    "OpenBlock",
    "CloseBlock",
  };
}
/* JavaCC - OriginalChecksum=3c776f1283a734cbed58dd3d3f89e521 (do not edit this line) */
