/* Generated By:JJTree: Do not edit this line. ConstDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ConstDecl extends SimpleNode {
  public ConstDecl(int id) {
    super(id);
  }

  public ConstDecl(CCALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d6fcbf6cdcb1cdf4ac9234f2f95c5c2f (do not edit this line) */
